var renderPDF=function(a){function K(){a(window).on("resize",function(c){l(d,!1)});a("#zoomOut").on("click",function(){var c=m-.2;c>=r&&(m=c,l(d,!0))});a("#zoomIn").on("click",function(){var c=m+.2;c<=4*r&&(m=c,l(d,!0))});a("#fullScreen").on("click",function(){screenfull.enabled?(screenfull.toggle(),document.addEventListener(screenfull.raw.fullscreenchange,function(){screenfull.isFullscreen?a("#fullScreen").attr("data-tooltip","Exit Full Screen").find("i").text("fullscreen_exit"):a("#fullScreen").attr("data-tooltip",
"Go Full Screen").find("i").text("fullscreen");l(d)})):showAlert("red","Your browser doesn't support full screen view.")});a(document).on("click","#commentBtn",function(c){0<a("#commentsModal").length&&a("#commentsModal").remove();c=_.template(a("#commentsTemplate").html());a("body").append(c({comments:k[d]}));a("#commentsModal").on("click","#commentsDel",function(b){confirm("Do you really want to delete note from bookmark?")&&getData({url:ctx+"/bookmark/pdf/page/delNote",data:{id:bookmarks[d]},success:function(g,
h){k[d]="";a("#commentBtn").attr("data-tooltip",k[d]).hide();a("#commentsModal").remove();showAlert("green","Note deleted successfully")}},{btn:a(this)})})});a(document).on("click","#bookmarkPdfPage",function(c){void 0===bookmarks[d]?(c=a("#notesModal"),0<c.length&&c.remove(),a("body").append(a("#notesTemplate").html()),a("#notesModal").on("click","#notesBtn",function(b){b=a("#notes").val();0<b.length&&a("#commentBtn").show().attr("data-tooltip",b.substr(0,120<b.length?120:b.length));postData({url:ctx+
"/bookmark/pdf/page/add",data:{courseId,pdfId,pdfPage:d,notes:b},success:function(g,h){showAlert("green",g.message);a("#notesModal").remove();bookmarks[d]=g.id;k[d]=g.notes;a("#bookmarkPdfPage").attr("data-tooltip","Delete bookmark").html('<i class="material-icons">bookmark</i>')}},{btn:a(this)})})):confirm("Are you sure you want to delete this bookmark?")&&getData({url:ctx+"/bookmark/delete",data:{id:bookmarks[d]},success:function(b,g){delete bookmarks[d];a("#commentBtn").hide();g.btn.attr("data-tooltip",
"Bookmark Page").html('<i class="material-icons">bookmark_border</i>');showAlert("green","Bookmark deleted successfully.")}},{btn:a(this)})});a(document).keydown(function(c){switch(c.which){case 37:y();break;case 39:z();break;default:return}c.preventDefault()})}function L(){e.globalAlpha=.5;e.font="20px sans-serif";e.fillStyle=A;var c=location.host+"\n"+B+"\n"+C,b=e.measureText(c).width;getRandomInt(.3,f.width/2);e.save();e.translate(getRandomInt(.2*f.width,.6*f.width),getRandomInt(.2*f.height,.6*
f.height));e.rotate(-Math.atan(f.height/f.width));e.fillText(c,-b/2,10);e.restore()}function M(){e.font="20px sans-serif";e.fillStyle="#000000";var c=D,b=e.measureText(c).width;e.save();e.translate(.5*f.width,f.height-500);e.fillText(c,-b/2,10);e.restore()}function t(c,b){void 0===bookmarks[c]?(a("#bookmarkPdfPage").attr("data-tooltip","Bookmark Page").html('<i class="material-icons">bookmark_border</i>'),a("#commentBtn").hide()):(a("#bookmarkPdfPage").attr("data-tooltip","Delete bookmark").html('<i class="material-icons">bookmark</i>'),
void 0!==k[c]&&0<k[c].length&&"true"===window.parent.courseBookmarkSupport&&a("#commentBtn").show().attr("data-tooltip",k[c].substr(0,120<k[c].length?120:k[c].length)));u=!0;v.addClass("loading");n.getPage(c).then(function(g){PDFVar=g;if(!b){var h=g.getViewport({scale:1});m=r=parseFloat((v[0].clientWidth/h.width).toFixed(2))}a("#scale_factor").html(":root {--scale-factor: "+m+"}");var p=(window.devicePixelRatio||1)/(e.webkitBackingStorePixelRatio||e.mozBackingStorePixelRatio||e.msBackingStorePixelRatio||
e.oBackingStorePixelRatio||e.backingStorePixelRatio||1);h=g.getViewport({scale:m*p});f.height=h.height;f.width=h.width;1<p&&(f.style.width=h.width/p+"px",f.style.height=h.height/p+"px");g.render({canvasContext:e,viewport:h}).promise.then(function(){u=!1;v.removeClass("loading");E&&(L(),1==c%5&&F&&M());document.scrollingElement.scrollTo(0,0);null!==q&&(t(q),q=null);g.getAnnotations().then(function(w){let G=[];w.forEach(H=>{H.url&&G.push(H)});w=G;let x=a("#annotation-layer");x.removeAttr("data-main-rotation").removeAttr("style").empty();
x.css({left:f.offsetLeft+"px",top:f.offsetTop+"px",height:f.height+"px",width:f.width+"px"});pdfjsLib.AnnotationLayer.render({viewport:h.clone({dontFlip:!0}),div:x.get(0),annotations:w,linkService:I,page:g})})})});document.getElementById("page_num").value=c}function l(c,b){u?q=c:t(c,b)}function y(){1>=d||(d--,l(d,!0))}function z(){d>=n.numPages||(d++,l(d,!0))}var n=null,d=1,u=!1,q=null,v=a(".pdfCont"),r=1,m=1,f=null,e=null,B=null,C=null,D=null,E=!1,k={},A="darkgrey",F=!1;const J=window["pdfjs-dist/web/pdf_viewer"],
I=new J.PDFLinkService;I.externalLinkTarget=J.LinkTarget.BLANK;return{init:function(){""!==a("#wcolor").val()&&(A=a("#wcolor").val());"true"===a("#wfixed").val()&&(F=!0);0>location.href.indexOf("/preview/")&&(B=SPUSER.email,C=SPUSER.phone,D=SPUSER.referCode);"true"===window.parent.courseBookmarkSupport&&0>location.href.indexOf("/preview/")?a("#bookmarkPdfPage").show():(a("#bookmarkPdfPage").hide(),a("#commentBtn").hide());-1<window.parent.location.hash.indexOf("&p=")&&(d=parseInt(window.parent.location.hash.split("&p=")[1]),
window.parent.location.hash="");f=document.getElementById("pdfCanvas");if(null==f)return!1;e=f.getContext("2d");a(document).off("contextmenu").on("contextmenu",function(b){return!1});var c={url:pdfUrl,data:{},success:function(b,g){void 0===b.isAvailable||b.isAvailable?(window.parent.coursePlayer.showAvailableContent("pdf",pdfId),g={url:b.url},0>location.href.indexOf("/preview/")&&void 0!==b.allowWatermark&&(E=b.allowWatermark),void 0!==b.p&&(g.password=parseJData(b.p,!0)),b.allowDownload&&a("#download").show(),
pdfjsLib.getDocument(g).promise.then(function(h){n=h;document.getElementById("page_count").textContent=n.numPages;t(d)})):window.parent.coursePlayer.showNotAvailableContent(b.startTime,b.endTime)}};getData(c,{});0>location.href.indexOf("/preview/")&&(c={url:ctx+"/bookmark/pdf/page/getAllByPdfId",data:{pdfId},success:function(b,g){for(i=0;i<b.result.length;i++)k[parseInt(b.result[i].pdfPage)]=b.result[i].notes,bookmarks[parseInt(b.result[i].pdfPage)]=b.result[i]._id}},getData(c,{}));document.getElementById("next").addEventListener("click",
z);document.getElementById("prev").addEventListener("click",y);a("#pageChangeForm").on("submit",function(b){b.preventDefault();b=parseInt(a("#page_num").val());if(!(1>b||b>n.numPages))return d=b,l(b),!1});K()}}}(jQuery);
